name: Promote

on:
  workflow_dispatch:
    inputs:
      message:
        description: "Message to echo"
        required: false
        default: "Hello from GitHub Actions"
      stage:
        description: "stage to echo"
        required: true

jobs:
  echo:
    runs-on: ubuntu-latest

    steps:
      - name: Print message
        run: echo "${{ github.event.inputs.stage }} ${{ github.event.inputs.message }}"
