name: Promote

on:
  workflow_dispatch:
    inputs:
      stage:
        required: true
      image:
        required: true
      imageTag:
        required: true

jobs:
  echo:
    runs-on: ubuntu-latest

    steps:
      - name: Print message
        run: echo "${{ github.event.inputs.stage }} ${{ github.event.inputs.image }}:${{ github.event.inputs.imageTag }}"
